baseurl = "."
languageCode = "en-us"
title = "Nix Theme"
theme = "hugo-theme-nix"

[params]
  GithubID = "mrseelig"
  TwitterID = "your_twitter"
  LinkedInID = "www.linkedin.com/mrseelig"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "your_name"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  Email = "your_email"
  About = "info_about_you"
  ProfilePicture = "https://image.ibb.co/gKtdJ5/gray_cog_the_rest_white.png"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
